version: "3"
services:
mymongo:
image: mongo:latest
container_name: "mymongo"
ports: -27017:27017
microservice-1-mongo:
image: microservice-1:latest
container_name: microservice-1-mongo
ports : -8085:8085
links: -mymongo